# vim:ft=tmux
## Support for 256-color
set -g default-terminal "xterm-256color"
set -ga terminal-overrides ',xterm-256color:Tc'
set -g status-interval 1

set-window-option -g mode-keys vi

set -g allow-passthrough on
set -ga update-environment TERM
set -ga update-environment TERM_PROGRAM

## Increse history limit
set -g history-limit 10000

## Command escape time
set -g escape-time 0

set -g repeat-time 1000

## Enable renumber window
set -g renumber-windows on

## Start window and pane with index 1
set -g base-index 1
setw -g pane-base-index 1

## Auto-title
set-window-option -g automatic-rename on
set-option -g set-titles on

## Enable mouse support
set -g mouse on

## Set ZSH as default shell
set-option -g default-shell /usr/bin/zsh
