source-file ~/.config/tmux/conf.d/general.conf
source-file ~/.config/tmux/conf.d/binds.conf
source-file ~/.config/tmux/conf.d/appearance.conf

source-file ~/.config/tmux/plugins/tpm.conf
run '~/.tmux/plugins/tpm/tpm'
