
#   ____  _           _
#  | __ )(_)_ __   __| |___
#  |  _ \| | '_ \ / _` / __|
#  | |_) | | | | | (_| \__ \
#  |____/|_|_| |_|\__,_|___/
#


#############################
# PREFIX & UNBINDS
#############################
# Odmapowanie domyślnego prefixu, 'q', 'x'
unbind-key C-b
unbind q
unbind x

# Nowy prefix
set-option -g prefix C-Space
bind-key C-Space send-prefix

#############################
# COPY / VIM MODE
#############################
# Ustawienia trybu vi w oknach
set-window-option -g mode-keys vi

# Skróty w trybie copy-mode
bind-key v copy-mode                       # wejście do trybu kopiowania
bind-key -T copy-mode-vi v send-keys -X begin-selection     # zaznaczanie
bind-key -T copy-mode-vi C-v send-keys -X rectangle-toggle # zaznaczenie prostokątne
bind-key -T copy-mode-vi y send-keys -X copy-selection-and-cancel # kopiowanie i wyjście
bind-key -T copy-mode-vi i send-keys -X cancel              # anulowanie zaznaczenia

#############################
# WINDOW NAVIGATION
#############################
bind-key h previous-window
bind-key l next-window

#############################
# PANE NAVIGATION
#############################
bind-key h select-pane -L
bind-key j select-pane -D
bind-key k select-pane -U
bind-key l select-pane -R

#############################
# PANE / WINDOW MANAGEMENT
#############################
bind-key q kill-pane   # zamykanie bieżącego panelu

#############################
# SPLIT-MODE (po prefix + s)
#############################
# Wejście w tryb split-mode
bind-key s switch-client -T split-mode

# Skróty w split-mode
bind-key -T split-mode v split-window -h -c "#{pane_current_path}"  # poziome dzielenie
bind-key -T split-mode h split-window -v -c "#{pane_current_path}"  # pionowe dzielenie
