## Unbinds
unbind-key C-b

set-option -g prefix C-Space

bind-key C-Space send-prefix

## Set vim-mode
set-window-option -g mode-keys vi

## Bindings
bind-key -T copy-mode-vi v send-keys -X begin-selection
bind-key -T copy-mode-vi C-v send-keys -X rectangle-toggle
bind-key -T copy-mode-vi y send-keys -X copy-selection-and-cancel


# Bind 's' (after prefix) to enter a new key table called 'split-mode'
bind-key s switch-client -T split-mode

# Define keybindings within the 'split-mode' table
# When in 'split-mode':
bind-key -T split-mode v split-window -h -c "#{pane_current_path}"
bind-key -T split-mode h split-window -v -c "#{pane_current_path}"

